"""
The "glue" between HTTP routes and the LangGraph agent graph.

This is where all the I/O that nodes themselves shouldn't do lives:
reading the user's chart context, fetching+decrypting their LLM key,
checking Binance connection and fetching live balances. All of THAT
happens here, ONCE, before the graph runs -- nodes only ever touch
the plain AgentState dict, never a DB session directly.
"""

import asyncio
import json
import uuid
from typing import AsyncIterator

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.agents.graph import agent_graph
from app.models.chart_context import ChartContext
from app.models.integration_key import IntegrationKey
from app.core.encryption import decrypt_value
from app.services.llm_key_service import get_active_llm_credentials
from app.services.news_cache_service import get_cached_news


async def _prepare_initial_state(
    db: AsyncSession,
    user_id: uuid.UUID,
    user_question: str | None = None,
    history: list[dict] | None = None,
    token_queue: asyncio.Queue | None = None,
) -> tuple[dict | None, dict | None]:
    """
    Common setup for both synchronous and streaming assistant execution.
    Returns (initial_state, error_response).
    """
    # 1. Chart context
    context_result = await db.execute(select(ChartContext).where(ChartContext.user_id == user_id))
    context = context_result.scalar_one_or_none()
    symbol = context.symbol if context else "BTCUSDT"
    timeframe = context.timeframe if context else "15m"

    # 2. LLM credentials -- compulsory
    llm_creds = await get_active_llm_credentials(db, user_id)
    if llm_creds is None:
        err = {
            "final_response": "No active LLM key is set (or it has expired). Please add one in settings first.",
            "intent": "general",
            "indicators": None,
            "news_items": None,
            "sentiment_summary": None,
            "risk_profile": None,
            "errors": ["No active/valid LLM key for this user"],
        }
        return None, err

    # 3. Binance integration
    binance_result = await db.execute(
        select(IntegrationKey).where(
            IntegrationKey.user_id == user_id,
            IntegrationKey.platform == "binance",
            IntegrationKey.is_active == True,  # noqa: E712
        )
    )
    binance_key = binance_result.scalar_one_or_none()

    binance_connected = False
    binance_api_key = None
    binance_api_secret = None
    if binance_key is not None:
        try:
            binance_api_key = decrypt_value(binance_key.encrypted_api_key)
            binance_api_secret = decrypt_value(binance_key.encrypted_api_secret)
            binance_connected = True
        except Exception:
            binance_connected = False

    # 4. News cache
    raw_news: list[dict] = []
    errors: list[str] = []
    try:
        raw_news = await get_cached_news(db)
    except Exception as exc:
        errors.append(f"sentiment_node: failed to fetch news: {exc}")

    # 5. Initial graph state
    initial_state = {
        "user_id": str(user_id),
        "symbol": symbol,
        "timeframe": timeframe,
        "user_question": user_question,
        "history": history or [],
        "token_queue": token_queue,
        "llm_provider": llm_creds["provider"],
        "llm_model_name": llm_creds["model_name"],
        "llm_api_key": llm_creds["api_key"],
        "binance_connected": binance_connected,
        "binance_api_key": binance_api_key,
        "binance_api_secret": binance_api_secret,
        "portfolio_balances": None,
        "raw_news": raw_news,
        "errors": errors,
    }
    return initial_state, None


async def run_trading_assistant(
    db: AsyncSession,
    user_id: uuid.UUID,
    user_question: str | None = None,
    history: list[dict] | None = None,
) -> dict:
    initial_state, err_resp = await _prepare_initial_state(db, user_id, user_question, history)
    if err_resp:
        return err_resp

    result = await agent_graph.ainvoke(initial_state)

    return {
        "final_response": result.get("final_response"),
        "intent": result.get("intent", "market"),
        "indicators": result.get("indicators"),
        "news_items": result.get("news_items"),
        "sentiment_summary": result.get("sentiment_summary"),
        "risk_profile": result.get("risk_profile"),
        "errors": result.get("errors", []),
    }


async def run_trading_assistant_stream(
    db: AsyncSession,
    user_id: uuid.UUID,
    user_question: str | None = None,
    history: list[dict] | None = None,
) -> AsyncIterator[str]:
    """
    Executes the trading assistant and yields Server-Sent Events (SSE).
    Tokens stream in real-time as they are generated by the LLM provider.
    """
    token_queue = asyncio.Queue()
    initial_state, err_resp = await _prepare_initial_state(
        db, user_id, user_question, history, token_queue=token_queue
    )

    if err_resp:
        yield f"data: {json.dumps({'type': 'done', **err_resp})}\n\n"
        return

    # Run the graph in background task so we can stream tokens from the queue concurrently
    task = asyncio.create_task(agent_graph.ainvoke(initial_state))

    try:
        while True:
            token = await token_queue.get()
            if token is None:
                break
            yield f"data: {json.dumps({'type': 'token', 'delta': token})}\n\n"

        result = await task

        yield f"data: {json.dumps({'type': 'done', 'final_response': result.get('final_response'), 'intent': result.get('intent', 'market'), 'indicators': result.get('indicators'), 'news_items': result.get('news_items'), 'sentiment_summary': result.get('sentiment_summary'), 'risk_profile': result.get('risk_profile'), 'errors': result.get('errors', [])})}\n\n"
    except Exception as exc:
        yield f"data: {json.dumps({'type': 'error', 'error': str(exc)})}\n\n"